FROM ubuntu:latest

LABEL maintainer=Xu@nCh3n

ENV TZ Asia/Shanghai
ENV LANG zh_CN.UTF-8

RUN apt-get update -y \
  && apt-get -y install --no-install-recommends wget \
  && apt-get -y install --no-install-recommends python3 python3-pip python3-dev\
  && apt-get -y install --no-install-recommends libxml2-utils \
  && apt-get clean \
  && apt-get autoclean \
  && rm -rf /tmp/* /var/lib/apt/lists/* /var/tmp/*

RUN cd /usr/bin \
  && ln -s python3 python \
  && python3 -m pip install --upgrade pip \
  && python3 -m  pip install --no-cache-dir watchdog requests -q

RUN  wget -O /home/Emby_WithWatchdog.py "https://gitlab.b1gfac3c4t.top:3443/xu4nch3n/watchdog_for_EmbyMedia/-/raw/main/Emby_WithWatchdog.py"

ENTRYPOINT ["python3"]
CMD ["/home/Emby_WithWatchdog.py"]